import React from 'react'

export default function Footer() {
  return (
    <footer className='p-4'>
Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse dolorem sit, officia nobis sapiente et perferendis facere doloremque aspernatur delectus non harum nihil sunt cumque exercitationem distinctio adipisci temporibus illo tempora, explicabo ipsam fugiat amet voluptate. Atque recusandae rem ullam dolor repudiandae. Praesentium unde vero officia consequatur eius, amet earum itaque saepe a quod nostrum quas quos excepturi, deleniti dolores expedita repellat non obcaecati quis magnam aliquid nam repellendus. Eum nam dignissimos exercitationem numquam, ea illum sed itaque ullam? Voluptatum corporis molestiae porro dignissimos rem impedit dolorem reiciendis voluptas hic nisi. Quasi et ipsum repudiandae neque, porro sit harum dolores consectetur assumenda ad itaque dicta laudantium magni deleniti iure rerum magnam! Explicabo perspiciatis eaque illum odio velit, quaerat tempore aut placeat necessitatibus praesentium voluptatibus eveniet animi esse quasi qui ipsa porro dicta natus aspernatur! Sit quos, unde accusamus ad recusandae voluptate odio veniam est assumenda inventore, officia totam enim sapiente voluptatibus alias aliquam? Asperiores at dolorum maxime? Deserunt ipsa sit aperiam atque in numquam temporibus consequuntur nihil. Officia natus enim maiores rem nisi ipsum ea voluptas magnam architecto sed, non, aliquam maxime fugit suscipit odit minima nihil nesciunt velit blanditiis ex tempora cum! Odit odio ipsum vitae aut, aliquid velit? Quo esse reprehenderit, ratione unde libero ipsam repellendus reiciendis dicta et ex error, doloribus laudantium voluptatibus. Molestias, quod? Maxime voluptas, tempore, incidunt dolores perferendis voluptatum exercitationem alias debitis eos, assumenda ea quas placeat tempora. Enim, officia? Dolores laudantium maxime reiciendis natus! Nostrum consectetur officia quasi harum, ut optio autem dolore, ipsa praesentium laudantium dicta consequuntur in ab adipisci ipsam perferendis rerum accusantium corrupti nam ea excepturi iste repudiandae? Adipisci voluptates blanditiis illo cumque explicabo dicta eaque atque sapiente corrupti necessitatibus, ducimus architecto quisquam placeat. Magnam commodi libero, dignissimos praesentium assumenda hic quo aliquam? Earum, nihil quis quo porro similique officiis?
    </footer>
  )
}
